# Generated by Django 4.1.5 on 2023-03-06 21:37

import DB.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is already taken, use another.'}, max_length=60, unique=True, validators=[DB.models.UnicodeUsernameValidator(), django.core.validators.MinLengthValidator(6)], verbose_name='username'),
        ),
    ]
