# Generated by Django 4.1.5 on 2023-03-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='favos_categories',
            new_name='favo_categories',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favos_products',
            new_name='favo_products',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='favos_tags',
            new_name='favo_tags',
        ),
    ]
