# Generated by Django 4.1.5 on 2023-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_product_price_store_rate_alter_product_rate_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
