# Generated by Django 4.0.6 on 2023-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='stores_images'),
        ),
        migrations.AlterField(
            model_name='branchimages',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='stores_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products_images'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='stores_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='users_images/default_profile_img.jpg', upload_to='users_images'),
        ),
    ]
